import { answerStatic } from "./copilotStatic";

// STATIC mode serves everything from pre-rendered JSON (web/public/static-data/,
// generated by api/scripts/export_static.py) with no backend at all -- how the
// GitHub Pages deployment runs. Live mode (local dev via ./run.sh) hits the
// real FastAPI server. Same `api.xxx()` call sites either way.
const STATIC = import.meta.env.VITE_STATIC === "true";
const LIVE_BASE = "/api";
const STATIC_BASE = `${import.meta.env.BASE_URL}static-data`;

async function liveReq(path, opts) {
  const res = await fetch(`${LIVE_BASE}${path}`, {
    headers: { "Content-Type": "application/json" },
    ...opts,
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      const body = await res.json();
      detail = body.detail || detail;
    } catch {
      /* ignore */
    }
    throw new Error(detail);
  }
  return res.json();
}

async function staticReq(path) {
  const res = await fetch(`${STATIC_BASE}${path}.json`);
  if (!res.ok) throw new Error(`Static data not found: ${path}`);
  return res.json();
}

function endpoint(staticPath, livePath, liveOpts) {
  return () => (STATIC ? staticReq(staticPath) : liveReq(livePath, liveOpts));
}

export const api = {
  health: endpoint("/health", "/health"),
  vendors: endpoint("/vendors", "/vendors"),
  vendor: (id) => (STATIC ? staticReq(`/vendors/${id}`) : liveReq(`/vendors/${id}`)),
  ruleInspector: (id, asOf) =>
    STATIC ? staticReq(`/vendors/${id}/rule-inspector`) : liveReq(`/vendors/${id}/rule-inspector${asOf ? `?as_of=${asOf}` : ""}`),
  findings: (id) => (STATIC ? staticReq(`/vendors/${id}/findings`) : liveReq(`/vendors/${id}/findings`)),
  disputeLetter: (id, invoiceId) =>
    STATIC ? staticReq(`/vendors/${id}/invoices/${invoiceId}/dispute-letter`) : liveReq(`/vendors/${id}/invoices/${invoiceId}/dispute-letter`),
  contractTests: (id) => (STATIC ? staticReq(`/vendors/${id}/contract-tests`) : liveReq(`/vendors/${id}/contract-tests`)),
  ciHistory: (id) => (STATIC ? staticReq(`/vendors/${id}/ci-history`) : liveReq(`/vendors/${id}/ci-history`)),
  forecast: (id, months = 36) => (STATIC ? staticReq(`/vendors/${id}/forecast`) : liveReq(`/vendors/${id}/forecast?months=${months}`)),
  negotiateVendor: (id) => (STATIC ? staticReq(`/vendors/${id}/negotiate`) : liveReq(`/vendors/${id}/negotiate`, { method: "POST" })),
  dashboard: endpoint("/dashboard", "/dashboard"),
  calendar: endpoint("/calendar", "/calendar"),
  diff: (pairId) => (STATIC ? staticReq(`/diff/${pairId}`) : liveReq(`/diff/${pairId}`)),
  presign: (proposalId, seats) =>
    STATIC ? staticReq(`/presign/${proposalId}`) : liveReq(`/presign/${proposalId}${seats ? `?seats=${seats}` : ""}`),
  negotiateProposal: (proposalId, seats) =>
    STATIC
      ? staticReq(`/presign/${proposalId}/negotiate`)
      : liveReq(`/presign/${proposalId}/negotiate${seats ? `?seats=${seats}` : ""}`, { method: "POST" }),
  copilotAsk: async (question) => {
    if (STATIC) {
      const graph = await staticReq("/graph");
      return answerStatic(question, graph);
    }
    return liveReq("/copilot/ask", { method: "POST", body: JSON.stringify({ question }) });
  },
  suggestedQuestions: endpoint("/copilot/suggested-questions", "/copilot/suggested-questions"),
  connectors: endpoint("/connectors", "/connectors"),
  pollMockErp: () => liveReq("/connectors/mock-erp/poll", { method: "POST" }),
  resetMockErp: () => liveReq("/connectors/mock-erp/reset", { method: "POST" }),
  pollCsvWatch: () => liveReq("/connectors/csv-watch/poll", { method: "POST" }),
};

export function fmtMoney(v) {
  if (v == null) return " - ";
  const n = typeof v === "string" ? parseFloat(v) : v;
  if (Number.isNaN(n)) return v;
  return n.toLocaleString("en-US", { style: "currency", currency: "USD" });
}

export function fmtNum(v, digits = 1) {
  if (v == null) return " - ";
  const n = typeof v === "string" ? parseFloat(v) : v;
  if (Number.isNaN(n)) return v;
  return n.toLocaleString("en-US", { maximumFractionDigits: digits });
}
