"""Exports every API response the frontend needs as static JSON files, for
a fully static deployment (GitHub Pages) that needs no backend server at
all. Every file is byte-identical to what the live FastAPI app returns --
generated by actually calling the app in-process via TestClient, not by
reimplementing the logic.

Run: python api/scripts/export_static.py
Output: web/public/static-data/**/*.json
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fastapi.testclient import TestClient  # noqa: E402

from app.main import app  # noqa: E402
from app.pipeline.loader import VENDOR_IDS  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "web" / "public" / "static-data"


def dump(rel_path: str, data):
    p = OUT / rel_path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2))


def main():
    with TestClient(app) as client:
        def get(path):
            r = client.get(path)
            r.raise_for_status()
            return r.json()

        def post(path):
            r = client.post(path)
            r.raise_for_status()
            return r.json()

        dump("health.json", get("/api/health"))

        vendors = get("/api/vendors")
        dump("vendors.json", vendors)

        all_findings = []
        for vid in VENDOR_IDS:
            dump(f"vendors/{vid}.json", get(f"/api/vendors/{vid}"))
            dump(f"vendors/{vid}/rule-inspector.json", get(f"/api/vendors/{vid}/rule-inspector"))
            dump(f"vendors/{vid}/ci-history.json", get(f"/api/vendors/{vid}/ci-history"))
            dump(f"vendors/{vid}/forecast.json", get(f"/api/vendors/{vid}/forecast?months=36"))
            dump(f"vendors/{vid}/contract-tests.json", get(f"/api/vendors/{vid}/contract-tests"))
            dump(f"vendors/{vid}/negotiate.json", post(f"/api/vendors/{vid}/negotiate"))

            findings_resp = get(f"/api/vendors/{vid}/findings")
            dump(f"vendors/{vid}/findings.json", findings_resp)
            all_findings.extend(findings_resp["findings"])
            for f in findings_resp["findings"]:
                dump(
                    f"vendors/{vid}/invoices/{f['invoice_id']}/dispute-letter.json",
                    get(f"/api/vendors/{vid}/invoices/{f['invoice_id']}/dispute-letter"),
                )

        dump("dashboard.json", get("/api/dashboard"))
        dump("calendar.json", get("/api/calendar"))
        dump("diff/datavault.json", get("/api/diff/datavault"))
        dump("presign/talentbridge_proposal.json", get("/api/presign/talentbridge_proposal"))
        dump("presign/talentbridge_proposal/negotiate.json", post("/api/presign/talentbridge_proposal/negotiate"))
        dump("copilot/suggested-questions.json", get("/api/copilot/suggested-questions"))
        dump("connectors.json", get("/api/connectors"))

        vendor_names = {v["vendor_id"]: v["vendor_name"] for v in vendors["vendors"]}
        invoice_counts = {v["vendor_id"]: v["invoice_count"] for v in vendors["vendors"]}
        dump("graph.json", {"findings": all_findings, "vendor_names": vendor_names, "invoice_counts": invoice_counts})

    count = len(list(OUT.rglob("*.json")))
    print(f"Exported {count} static JSON files to {OUT}")


if __name__ == "__main__":
    main()
